# Generated by Django 3.2.8 on 2021-10-06 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('price_in_coins', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images/')),
                ('number_of_uses', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Awards',
            },
        ),
        migrations.CreateModel(
            name='CollectedAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_note', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('awards', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='awards.awards')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Collected Awards',
            },
        ),
    ]
