# Generated by Django 3.0 on 2021-07-20 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivo', '0003_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='annual_budget',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='initial_budget',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
    ]
