# Generated by Django 3.0 on 2021-07-20 10:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('motivo', '0005_attempt_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='attempt',
        ),
        migrations.AddField(
            model_name='attempt',
            name='challenge',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='motivo.Challenge'),
            preserve_default=False,
        ),
    ]
