# Generated by Django 3.0 on 2021-07-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motivo', '0006_auto_20210720_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='coins_to_win',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='description',
        ),
    ]
