# Generated by Django 3.0 on 2021-07-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivo', '0009_auto_20210720_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='file',
            field=models.FileField(upload_to='uploads/attempts/'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='image',
            field=models.ImageField(upload_to='uploads/images/'),
        ),
    ]
