# Generated by Django 3.0 on 2021-07-20 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motivo', '0012_auto_20210720_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='challenge',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='motivo.Challenge'),
        ),
    ]
