# Generated by Django 3.0 on 2021-07-20 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('motivo', '0013_auto_20210720_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='confirmed_by_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/attempts/'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='coins_to_win',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
