# Generated by Django 3.0 on 2021-07-26 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motivo', '0014_auto_20210720_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='collected_coins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('price_in_coins', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images/')),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='motivo.Challenge')),
            ],
        ),
    ]
