# Generated by Django 3.0 on 2021-07-26 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('motivo', '0015_auto_20210726_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='challenge',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='motivo.Challenge'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='confirmed_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='awards',
            name='price_in_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='awards',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='coins_to_win',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='annual_budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='collected_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='initial_budget',
            field=models.IntegerField(default=0),
        ),
    ]
