# Generated by Django 3.0 on 2021-07-27 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivo', '0016_auto_20210726_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
