# Generated by Django 3.2.7 on 2021-10-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
