# Generated by Django 3.2.5 on 2021-08-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
