# Generated by Django 3.2.7 on 2021-10-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivo', '0002_alter_challenge_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectedawards',
            name='user_note',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
