# Generated by Django 3.2.8 on 2021-10-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_annualbudgetmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualbudgetmanagement',
            name='title',
            field=models.CharField(default='tmp', max_length=255),
            preserve_default=False,
        ),
    ]
