# Generated by Django 3.2.8 on 2021-10-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_annualbudgetmanagement_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualbudgetmanagement',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('declined', 'declined'), ('waiting', 'waiting')], default='waiting', max_length=32),
        ),
    ]
