# Generated by Django 3.2.8 on 2021-10-06 09:34

import apps.challenges.validators
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='uploads/images/')),
            ],
            options={
                'verbose_name': 'Challenge category',
                'verbose_name_plural': 'Challenge category',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('coins_to_win', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/challenge_files/', validators=[apps.challenges.validators.validate_file_size])),
                ('number_of_attempts', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challengecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                # ('confirmed_by_admin', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/attempts/')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('challenge', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'To be approved',
                'verbose_name_plural': 'To be approved',
            },
        ),
    ]
