# Generated by Django 3.2.8 on 2021-10-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('declined', 'declined'), ('waiting', 'waiting')], default='waiting', max_length=32),
        ),
    ]
