# Generated by Django 3.2.8 on 2021-10-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motivo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectedawards',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='collectedawards',
            name='user',
        ),
        migrations.DeleteModel(
            name='Awards',
        ),
        migrations.DeleteModel(
            name='CollectedAwards',
        ),
    ]
